FROM mcr.microsoft.com/azureml/onnxruntime:latest

WORKDIR /code

RUN apt-get install -y cmake protobuf-compiler libprotoc-dev

RUN pip install pillow onnx

COPY model32/cvexport.manifest .
COPY labels.txt .
COPY lenna.png .
COPY model32/model.onnx .
#COPY model.zip .
RUN mkdir python
COPY python/cntk_predict.py        python 
COPY python/object_detection.py    python 
COPY python/onnxruntime_predict.py python

CMD python python/onnxruntime_predict.py lenna.png
